name: Public Npm Beta

on:
  push:
    branches: ["dev*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - uses: pnpm/action-setup@v2
        if: ${{ contains(steps.package-version.outputs.current-version,'beta')}}
        with:
          version: 7.21.0

      - name: Install and Build
        run: |
          pnpm install
          pnpm run build # 这是我的项目的打包命令，你也可以改成你的

      - name: "Publish to the npm registry"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: "beta"
