name: Publish Npm

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2
        with:
          version: 7.21.0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install and Build
        run: |
          pnpm install
          pnpm run build
      - name: "Publish to the npm registry"
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
